### ISSUE TITLE
Using GPU instead of CPU 

### ISSUE THREAD

**Issue by finiteautomata** [MilaNLProc/contextualized-topic-models#10]
* Contextualized Topic Models version: 1.4.1
* Python version: 3.6.9
* Operating System: Ubuntu

I was trying to run the basic example on a couple of texts. However, it takes a long time when running on CPU only, and the model is not receiving a `device` argument to make it use the GPU

Is there an easy way to do that without reimplementing everything?

**Comment by vinid** [comment]
Hi!

this sounds weird, it should run by default on GPU. You won't find `device` because we are using the old `.cuda()` method to move stuff from CPU to GPU (and thanks for pointing this out, we should update this to the new `.to(device)` approach).

Which part is taking a lot of time? is torch.cuda.device_count() returning 1?

**Comment by finiteautomata** [comment]
My error. I thought it was because `device` wasn't being set anywhere but it was an issue with CUDA drivers.

I have two GPUs (`torch.cuda.device_count()` returns 2) however it now works fine

Thanks!
