### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe Multithread problem on Windows

### ISSUE THREAD

**Issue by 18222278799** [MilaNLProc/contextualized-topic-models#107]
* Contextualized Topic Models version:
* Python version:
* Operating System:

### Description

When I use windows+pytorch+pycharm.

I meet     ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

It seems to be a Multithread problem. (from other web seems to modify num_workers to 0) But I dont know how to fix it in CTM.

**Comment by vinid** [comment]
Hi!

can you tell me which line generates the error?

You should be able to set

```num_data_loader_workers=0```

in the initialization of the CTM object (either ZeroShotTM or CombinedTM). 

See it [here](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/contextualized_topic_models/models/ctm.py#L48)

**Comment by 18222278799** [comment]
Thank you very much for your help!  And I have another question. Does the model apply unsupervised dataset (I have 500,000 sentences)? what other operations do I need to do when using CTM or Kitty?

**Comment by vinid** [comment]
You can follow one of the [tutorials](https://contextualized-topic-models.readthedocs.io/en/latest/introduction.html#tutorials) to get a better idea of how to run everything. You should be able to run the tutorials on your data by changing a few lines of code.

Important thing: since your dataset is very big, you definitely need to have a GPU to run this.
