### ISSUE TITLE
Predicted topic distribution for documents varies

### ISSUE THREAD

**Issue by tholor** [MilaNLProc/contextualized-topic-models#12]
* Contextualized Topic Models version: 1.4.2
* Python version: 3.7.6
* Operating System: Ubuntu 18.04

### Description

I want to extract the topic distribution for my documents (after having fitted the model). 
For example, I want to use this to show the "top 10" documents for every topic.

It's not clear how to do this in the library. Using `ctm.get_thetas()` doesn't seem to work for me here. 

### What I Did

Following your [example notebook](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/examples/topic-modeling.ipynb) I tried:

```
distribution = ctm.get_thetas(training_dataset)[8] # topic distribution for the eight document
print(distribution)
```

However, if I run the example notebook and execute the cell with the above code multiple times, the output of distribution changes. Is this expected? From my understanding, the model should be in pure inference mode and multiple calls with the same docs should result in the same topic probabilities.  Why is that the case?

**Comment by vinid** [comment]
Hello! that distribution is sampled from the network and that's why you see that it changes every time you run that line of code. What you can do is sampling multiple times to get a more reliable estimate.

In the [multilingual notebook](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/examples/multilingual-topic-modeling.ipynb) we show an example on how to do it.

Hope this helps :)

**Comment by tholor** [comment]
Hey @vinid , 
Got it. That makes a lot of sense. Thanks a lot for your quick reply!
