### ISSUE TITLE
Large Dataset

### ISSUE THREAD

**Issue by raymondsim** [MilaNLProc/contextualized-topic-models#130]
* Contextualized Topic Models version:
* Python version: 3.7
* Operating System: Mac OS Monterey

### Description

BOW size is capped around 32k based on my experiment. I noticed that #129 also mentioned the same problem but I was wondering if there's any way I could expand the capability of CTM working on larger vocab size. i.e. with better GPU?

I do not wish to reduce vocab size because I used a pre-trained encoder to create the custom embedding and would like to incorporate the topic-word distribution back into an encoder-decoder model. So changing vocab size will make it harder to make comparison between CTM output and the model.

Thanks in advance!

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/58366147/229545706-fd92a31a-2f5f-4924-aaec-260dede11c4d.png">

**Comment by vinid** [comment]
Hello!

You could modify [this part](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/contextualized_topic_models/networks/inference_network.py#L127).

I think the issue is the following one:
CombinedTM takes in input contextualized representations and the vocab. 
Contextualized representations are expanded to match the dimension of the vocab.

You could add a Linear layer that reduces the size of the vocab before concatenation. 

I believe this should improve performance

**Comment by raymondsim** [comment]
Hi,

I tried to add it like this but still doesnt work.

Is this what you meant by adding a linear layer?

35000 is my vocab size. My desired size is 52k.
![image](https://user-images.githubusercontent.com/58366147/229664820-8321caee-bff9-4a6c-ac45-523b3b2422d0.png)

Thanks in advance.

**Comment by raymondsim** [comment]
Hi,

Thanks for your help! I tried to use a more powerful CPU to compute 52k vocab and it works well without constraining embedded dimensions.

Thanks!
