### ISSUE TITLE
Perplexity

### ISSUE THREAD

**Issue by hosseinfani** [MilaNLProc/contextualized-topic-models#136]
Hi there,
I'm wondering the package offers the perplexity score on a held-out set in its evaluation.measures or model evaluation?

I see that it uses gensim for coherence metrics. Gesim also has perplexity.  

Would be great if perplexity added or any help to code it using existing functions of the library would be appreciated.

Thank you.

**Comment by vinid** [comment]
Hello!

We are currently not planning the implementation of perplexity in the lib. However, ETM implements a version of perplexity that might be useful as a starting point (since ETM is another neural topic model, it might be a good place to start from)

https://github.com/adjidieng/ETM/blob/81b839f16d3c168ac2c5c22daff18d924962c075/etm.py#L273

**Comment by hosseinfani** [comment]
@vinid thanks for the help. I try it and hopefully send a pr for ctm.

**Comment by vinid** [comment]
Awesome!
