### ISSUE TITLE
Predict topics for unseen documents

### ISSUE THREAD

**Issue by sithu31296** [MilaNLProc/contextualized-topic-models#22]
I have a question about predicting the topics for documents.

Can I predict the topics of the documents which are different from the trained documents? For example, I will train with technology related documents but in prediction, i will try with management related documents. Will it still give reasonable topics or should i retrain the model on management related documents?

I also saw the discussion in #4 and tried the following code

```python
ctm.get_topic_lists()[predicted_topics[0]]
```
but this `get_topic_lists()` is from the trained technology documents which are unrelated topics from management documents. So, according to this, there is clearly no chance of getting management topics because we are mapping with unrelated topic lists.

Is my question understandable? I'm quite new to this topic modelling field. So, this is quite confusing to me.

Please help me.

**Comment by silviatti** [comment]
Hi! 
When you train a topic model, the model learns to cluster the training documents into K fixed topics. So when you predict the topics on an unseen document, you will get the distribution of the topics that you have learned during training. In other words, if you train the model on technology-related documents and then predict on management-related documents, the model will try to fit the topics it has learned during training on the unseen documents. The results will be poor because the testing documents belong to a different domain. 

One solution is then to train on the whole corpus of documents (the model will automatically understand if two documents belong to different domains). Otherwise, you can train two different models. But the preferred solution depends on your objective.  

Hope I have been helpful :) 

Silvia

**Comment by sithu31296** [comment]
Thanks for your fast reply. That is quite useful. I confused because I thought topic modeling is an unsupervised case. Thanks for your help.
