### ISSUE TITLE
failing to predict topics in unseen documents

### ISSUE THREAD

**Issue by arianpasquali** [MilaNLProc/contextualized-topic-models#27]
* Contextualized Topic Models version: 1.5.3
* Python version: 3.6.9
* Operating System: google colab

### Description
Following the colab tutorial I trained the model using the wikipedia dataset. 
Now I am trying to follow the documentation to apply the model on new documents as described at [here](https://github.com/MilaNLProc/contextualized-topic-models#predict-topics-for-unseen-documents) and slightly different way [here described in this notebook](https://render.githubusercontent.com/view/ipynb?commit=5e3c8b28984a0c99ffc03001f60f7f32a7d28da0&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4d696c614e4c50726f632f636f6e7465787475616c697a65642d746f7069632d6d6f64656c732f356533633862323839383461306339396666633033303031663630663766333261376432386461302f6578616d706c65732f6d756c74696c696e6775616c2d746f7069632d6d6f64656c696e672e6970796e62&nwo=MilaNLProc%2Fcontextualized-topic-models&path=examples%2Fmultilingual-topic-modeling.ipynb&repository_id=253079431&repository_type=Repository#Test-the-model-on-unseen-documents-in-unseen-languages) . Both ways I get the same error. What am I missing?

### What I Did

```
test_handler = TextHandler("my_dataset_english.txt")
test_handler.prepare() # create vocabulary and training data

# generate BERT data
testing_bert = bert_embeddings_from_file("my_dataset_english.txt", "distilbert-base-nli-mean-tokens")

testing_dataset = CTMDataset(test_handler.bow, testing_bert, test_handler.idx2token)
# n_sample how many times to sample the distribution (see the doc)
ctm.get_thetas(testing_dataset, n_samples=20)
```

![error](https://user-images.githubusercontent.com/200721/98307128-621cb900-1fc5-11eb-8e58-9f4919b1d90d.png)

**Comment by vinid** [comment]
Hello @arianpasquali,

I might need to explore this more in detail tomorrow morning but I think the problem is that you are probably using the "combined" model in training (as you told me you used the colab notebook).

The "combined" model, uses the bag of words as input; this input is concatenated to bert embeddings. At test time, you need a bag of word of the same size as the one used in training to get the results. Thus, if you generate the bag of word for the documents they need to be consistent with the one you used in training*.

What is probably happening in your case is that "my_dataset_english.txt" creates a bag of words that is different from the one used during training.

The **contextual model** uses just the bert embeddings in input to the model.

Assuming this is the problem, you can simply change the `inference_type` parameter of the `CTM` model to **contextual**". This won't use any bag of word as input to the model (it wil be just used as target). And thus, at test time you will only need to pass the bert embeddings (that are of the same size as input).

Happy to add more details if needed or if I was not clear enough.

*a `.transform()` behaviour has the one provided by many sklearn packages would indeed solve the problem: as a test time you might want to use the same vectorizer you used in training. However, it is something we currently do not support. The only thing you can do with the combined model is getting the topic for the training documents.

**Comment by arianpasquali** [comment]
Thank you for the quick reply @vinid . I will try again.
