### ISSUE TITLE
use case / classify feeds and articles

### ISSUE THREAD

**Issue by x0rzkov** [MilaNLProc/contextualized-topic-models#3]
Hi,

Hope you are all well !

I work on a rss news feed aggregator and I d like to classify them with a model.
url: https://github.com/ncarlier/feedpushr.

Being quite new to nlp related fields, I was wondering if is it possible to train it with your package in order to get contextualized topics for articles or feeds ?

Thanks in advance for your inputs and insights about that question.

Cheers,
X

**Comment by vinid** [comment]
Hi!

Sorry for the late reply! I'll write down a few things that came to my mind and share a few pointers you might find interesting.

There quite a few things you could try. The good thing about topic models is that they are unsupervised, so, to answer your question, you might get some interesting results by using your dataset. If you follow the ipynb you should be easily able to get the topics just by providing a simple list of texts (note that however, articles that are too long will be cut since BERT has an input length limit). (Ping me if you need more help)

Moreover, you could also consider applying some methods for document embeddings. 

+ you can use Doc2Vec, that is quite reliable (although there are newer options) https://medium.com/wisio/a-gentle-introduction-to-doc2vec-db3e8c0cce5e
+ we used https://github.com/UKPLab/sentence-transformers for sentence embeddings, but also this is pretty useful https://static.googleusercontent.com/media/research.google.com/it//pubs/archive/46808.pdf) 

Once you have those embeddings you can learn a classifier (assuming you have some labeled samples) and see what comes out from that. If you generate document embeddings you can also see which documents are similar to each other, and you might discover something interesting.

Hope you find this useful!
Best :)
Fede
