### ISSUE TITLE
Explanation on ZeroShotTm working

### ISSUE THREAD

**Issue by subho22** [MilaNLProc/contextualized-topic-models#47]
Can you explain the internal working of ZeroShotTm as it doesn't uses BOW approach . The paper didn't highlighted about the ZeroShotTm  . How does the topic get derived? And how does it predict for unseen documents and calculate the probability of the topics

**Comment by silviatti** [comment]
Hi!

You can find the full description of the Zero-shot model here: https://arxiv.org/pdf/2004.07737v1.pdf. 
In the paper, we called the model "contextual TM". However, we recently decided to rename it in the code to distiguinsh it from the CombinedTM. We are probably going to change the name in the EACL paper too. 

The basic idea of the Zero-shot model is to use the Variational Autoencoder (VAE) architecture to infer the topics, but replace the input Bag-of-words (BOW) representation of a document with its contextualized representation (such as obtained from BERT). Since the model is based on a VAE, we get the topics from the weight matrix that uses the hidden layer representation to reconstruct the document BOW.

About the inference of the topic distribution of an unseen document, you just need the contextualized representation of the document as input of the model. Then, the hidden layer representation of the VAE represents the topic distribution of the given document. 

If you have any other question about the model, don't hesitate to ask!

Silvia

**Comment by subho22** [comment]
Hi Silva,

Thanks for the explanation . I have gone through the architecture diagram. Can you explain a bit about the mean and the variance used in the diagram. And can you explain a bit about reconstructing the BOW document. I didn't get the BOW document in here.

**Comment by silviatti** [comment]
The mean and variance are the parameters of a distribution that the VAE learns, from which the VAE samples the topic-document representation. This happens in all the VAE-based topic models. For more details, here's the original paper that describes the VAE: [https://arxiv.org/pdf/1511.06038.pdf](https://arxiv.org/pdf/1511.06038.pdf). And this one describes ProdLDA, which is the VAE-based model that we extend: [https://arxiv.org/abs/1703.01488](https://arxiv.org/abs/1703.01488). 

About the reconstruction of the BOW document, this is still something that most of the VAE-based models have in common. Once you have sampled the document representation from the above-mentioned distribution, you need to reconstruct the document. You do so by multiplying the document representation for a weight matrix (dimensions: `number of topics X number of words in the vocabulary`). (Refer to the VAE and ProdLDA papers for further details.)

In our particular case, the input of the model is the contextualized representation of a document, but the final layer of the network is the document in its BOW representation. We need the BOW somewhere in the VAE architecture. Otherwise, we would lose the information about the words in the documents and we wouldn't be able to understand which words are the most likely in a given topic. Refer to these papers for details: [CombinedTM](https://arxiv.org/pdf/2004.03974.pdf) and [ZeroShotTM](https://arxiv.org/pdf/2004.07737v1.pdf).

Hope this helps :)

Silvia

**Comment by subho22** [comment]
Thanks for the explanation..
