### ISSUE TITLE
Multilingual BERT models

### ISSUE THREAD

**Issue by abrahami** [MilaNLProc/contextualized-topic-models#52]
* Contextualized Topic Models version:
* Python version: 3.8
* Operating System: linux

### Description

I would like to train a topic model over a multilingual corpus (most of the corpus is English, but ~20% is French, German etc...)
Can I use the combinedTM model for that? 
I guess I should use a multilingual BERT model to represent my sentences and the rest of your model pipeline should work fine - right?

thanks a lot!

**Comment by vinid** [comment]
Hello @abrahami!

If you have a multilingual corpus, you are going to have a multilingual shared vocab. Thus, you can totally do that, I am curious about the topic you are going to get (I assume they will share words).

Note that, doing testing with CombinedTM is [a bit different](https://github.com/MilaNLProc/contextualized-topic-models#training-and-testing-with-combinedtm) as you have to use something that handles the missing words in the BoW. Given this problem, if your documents are not too long, I'd use the ZeroShotTM model.

**Model**
You can use the standard [multilingual](https://huggingface.co/bert-base-multilingual-cased) BERT model or you can use one of the multilingual models from [sentence-transformers](https://www.sbert.net/docs/pretrained_models.html#multi-lingual-models) that have generally nice results (note check if the languages you have are covered in the model you choose).

**On how I'd use ZeroShotTM** (it might not be what you are looking for, but might be useful to you so I write this anyway :))
I'd use the English documents as the training set (because you said they are the greatest part) and I'd use the remaining documents for testing, i.e. predicting their topics. However, if you aim to obtain topics in multiple languages this may not be your case because you will get topics in English only. 

Happy to help more if needed :)

**Comment by abrahami** [comment]
Great, thanks @vinid for a quick and informative answer!

In my case "documents" are actually communities (subreddits textual content).
Although I really like the ZeroShotTM model idea, I think that the CombinedTM model is a better fit here.

I'll be happy to share results once I have,
thanks a lot!

**Comment by vinid** [comment]
That makes sense! and thank you very much :)


(one thing I forgot to mention: you might want to reduce a bit the vocab by doing some pre-processing (a big vocab will make the model difficult to train since the neural network will need to reconstruct a large BoW))
