### ISSUE TITLE
Evaluation Measure, same input for LDA and CTM

### ISSUE THREAD

**Issue by Rezi27** [MilaNLProc/contextualized-topic-models#67]
Hello Silvia, hello Federico,
thank you very much for your fantastic work. I have a question about the evaluation technique. In your Google Colab tutorial in the evaluation part to compare coherence scores, for both models, LDA and CTM, you use the same texts input (texts=lda_text). Is this an intention that both models get the same input or is it a bug or a mistake? I guess in CTM model, texts input should be "training_contextual_document" and not "training_bow_documents"?

Here is the link to the notebook I mentioned: https://colab.research.google.com/drive/1wVWHe8xHasnUbzNs40MwlkJsUhvN98se?usp=sharing#scrollTo=E2GYCcydstJW

Please see the screenshot.

Thanks again, looking forward to your reply.

Best regards
Rezo

![Screenshot](https://user-images.githubusercontent.com/45456016/118400776-5f310e00-b663-11eb-96b1-a5429f828411.jpg)

**Comment by vinid** [comment]
Hello @Rezi27!

To evaluate the CTM model we use the `training_bow_documents` data because the `training_contextual_documents` contains text that is not clean.

The CTM(s) model, when you run the `ctm.get_topics()` method will return words that overlap with the `training_bow_documents` and not with the `training_contextual_documents`.

The NMPI coherence "compares" the topics with the words in the text and using the unpreprocessed documents will mess up the computation. 

If this is not clear I am happy to add more details :)

**Comment by Rezi27** [comment]
Hi Federico,
ok all right, thank you very much for your very quick reply, now I understand.
So in other words `ctm.get_topics()` takes the words from the training_bow_documents pool, right?
As I understand it is desired that the topics are not represented by unnecessary words and therefore the topics are "limited" to choose from and be represented by the words from training_bow_documents pool?

Thank you so much, you helped me a lot.

**Comment by vinid** [comment]
Yes!

If instead of reconstructing the BoW with the preprocessed documents we used the unpreprocessed one, we would get "messy topics". However, the information provided by the unpreprocessed documents is important (we want to use the unpreprocessed documents because we want to use all the information that models like BERT can give us).

**Comment by Rezi27** [comment]
In your paper you give a definition of NPMI as follows:
"It measures how much the top-10 words of a topic are related to each other, considering the
empirical frequency of the words computed on the original corpus.  is a symbolic metric and relies on co-occurrence."

So you say that this original corpus is training_bow_documents, right?
But I don't get one thing, how is it possible that CTM is trained on training_contextual_documents (because of BERT), but it is evaluated on training_bow_documents? Because when the model is trained on training_contextual_documents, should the topics suggested from that model not be also from the same data?

**Comment by vinid** [comment]
Hi :)

Two things might be worth mentioning to better understand this:

- The models are trained to reconstruct the BoW.
- The topic model can give us the topics that are the list of lists words

It is true that the input of CTM is `training_contextual_documents` but the model is still used to reconstruct the BoW. Since we reconstruct the BoW, the topics we'll get from the topic model will be made of the words that appear in the BoW. 

This is why when we evaluate the coherence we compute it on the documents that are also used to generate the BoW. 

Instead, if we wanted to evaluate how well the model was able to reconstruct the BoW, we would need to give as input to the model the `training_contextual_documents`. But this would be a different task, different from the evaluation of the coherence of the topics.

Does it make sense to you?

**Comment by Rezi27** [comment]
It does make sense, now I undestand. 
Thank you very much for your detailled explenation and support :)
