### ISSUE TITLE
Example code in Zeroshot topic model shows error.

### ISSUE THREAD

**Issue by Balamurugamuthumani** [MilaNLProc/contextualized-topic-models#69]
* Contextualized Topic Models version:1.8.1
* Python version:3.6.13
* Operating System:Linux 

### Description
Example code shown in https://github.com/MilaNLProc/contextualized-topic-models#zero-shot-topic-model

### What I Did
Just copy pasted the code that's put on read me to check the output

Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
Traceback (most recent call last):
  File "ctm.py", line 19, in <module>
    training_dataset = qt.fit(text_for_contextual=text_for_contextual, text_for_bow=text_for_bow)
AttributeError: 'TopicModelDataPreparation' object has no attribute 'fit'

**Comment by vinid** [comment]
Hello @Balamurugamuthumani :),

the code you see on GitHub is for version 2 (that breaks backward compatibility). You should install the new version with

`pip install -U contextualized-topic-models`

**Comment by Balamurugamuthumani** [comment]
Thanks. It working fine now

**Comment by Balamurugamuthumani** [comment]
![Screenshot from 2021-05-27 17-09-48](https://user-images.githubusercontent.com/45987790/119819781-603d2780-bf0e-11eb-97be-7c0a4cb918bc.png)

**Comment by silviatti** [comment]
Hi! 
The code snippet that you are using is just a code example. You should substitute "text_for_contextual" and "text_for_bow" with your own documents.  The function "get_topics" throws an error in the example because it requires the topics to be composed of at least 10 words, but the dictionary has only 6 words.  You'll see that if you replace the two lists with more documents, the error will not occur again. 

You can see a more complex example of the usage of Zero-shot TM [here](https://colab.research.google.com/drive/1bfWUYEypULFk_4Tfff-Pb_n7-tSjEe9v?usp=sharing).   

Silvia
