### ISSUE TITLE
Using DeCLUTR text embeddings in CTM

### ISSUE THREAD

**Issue by kingafy** [MilaNLProc/contextualized-topic-models#86]
I have trained declutur on legal dataset and I am trying to use it to extract topics using CTM.Currently process runs for infinite time without showing any output. Any idea why CTM does not work here.Is there any limiation on the models to be used?Cant we use our models on this framework?

**Comment by vinid** [comment]
Hello!

Can you share some more details about which dataset are you using/can you send a sample? 

Also, if you send me the code I can take a look!:)

Are you using a GPU?

**Comment by kingafy** [comment]
Data set is confidential.  The same data gets processed properly with the default model paraphrase-distilroberta-base-v1. The model which I have trained is in my local and I am loading from local directory.It gets stuck in the below code:-

tp = TopicModelDataPreparation("local folder")
training_dataset = tp.fit(text_for_contextual=unpreprocessed_corpus, text_for_bow=preprocessed_documents)

**Comment by vinid** [comment]
Got it, I think the issue is that we do not directly support DeCLUTR embeddings (we use sbert). However, there is a simple way
to bypass the issue by simply manually loading the embeddings.

See this notebook for an example that uses the default DeCLUTR model: https://colab.research.google.com/drive/1fXJjr_rwqvpp1IdNQ4dxqN4Dp88cxO97?usp=sharing

It should also work with your own fine-tuned model. 

Let me know if and how it works!
